version: '2'
services:
# ------ CONSUL SERVICE DISCOVERY ------ #
  consul:
    image: "gliderlabs/consul-server"
    container_name: consul
    ports:
      - "8500:8255"
    environment:
      SERVICE_IGNORE: "TRUE"
    command: -bootstrap
  registrator:
    image: "gliderlabs/registrator:latest"
    container_name: registrator
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    command: -internal consul://consul:8500
    depends_on:
      - "consul"

# ------ RELATIVELY SOCIAL APPLICATION SERVICES ----- #
  api-gateway:
    image: "relativelysocial/apigateway"- just: write some
- yaml:
  - [here, and]
  - {it: updates, in: real-time}

    container_name: "rs-apigateway"
    ports:
      - "4501:4567"
    depends_on:
      - "consul"
      - "registrator"
  auth-service:
    image: "relativelysocial/auth-service"
    container_name: "rs-authservice"
    ports:
      - "4502:4567"
    depends_on:
      - "consul"
      - "registrator"
  user-service:
    image: "relativelysocial/user-service"
    container_name: "rs-userservice"
    ports:
      - "4503:4567"
    depends_on:
      - "consul"
      - "registrator"
      - "api-gateway"
  relations-service:
    image: "relativelysocial/relations-service"
    container_name: "rs-relationsservice"
    ports:
      - "4504:4567"
    depends_on:
      - "consul"
      - "registrator"
      - "api-gateway"
  family-service:
    image: "relativelysocial/family-service"
    container_name: "rs-familyservice"
    ports:
      - "4505:4567"
    depends_on:
      - "consul"
      - "registrator"
      - "api-gateway"
# ------ NGINX FRONTEND CONTAINER ----- #
  web:
    image: nginx
    volumes:
      - ./frontend/relatively-frontend/:/usr/share/nginx/html
      - /etc/ssl/certs/:/etc/nginx/certs:ro
      - /etc/ssl/private/:/etc/nginx/private:ro
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt/archive/www.relativelysocial.com:/etc/nginx/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
